//===--- LeanBackend.cpp --------------------------------------------------===//
#include "LeanBackend.h"
#include "VCMachine.h"
#include "Z3Encode.h"
#include "llvm/Support/raw_ostream.h"

using namespace clang;
using namespace verify;

// Emission budget guarding against exponential blow-up: VCExprs are DAGs with
// shared sub-terms (heap store/select chains in particular), and printing them
// as a tree re-expands shared nodes. The budget caps total emitted nodes so the
// Lean scratch-pad export always terminates.
static unsigned LeanEmitBudget = 0;

static void printVCExprLean(const VCExpr *E, llvm::raw_ostream &OS, unsigned Prec = 0) {
  if (!E) {
    OS << "True";
    return;
  }
  if (LeanEmitBudget == 0)
    return;
  if (--LeanEmitBudget == 0) {
    OS << "/- … expression elided (too large for the Lean scratch-pad) -/";
    return;
  }
  auto paren = [&](unsigned P, auto Fn) {
    if (Prec > P)
      OS << "(";
    Fn();
    if (Prec > P)
      OS << ")";
  };
  switch (E->K) {
  case VCExpr::True:
    OS << "True";
    break;
  case VCExpr::False:
    OS << "False";
    break;
  case VCExpr::BoolLit:
    OS << (E->BoolVal ? "True" : "False");
    break;
  case VCExpr::IntLit:
    OS << E->IntVal;
    break;
  case VCExpr::Var:
    for (char C : E->Name) {
      if (C == '.')
        OS << "_";
      else
        OS << C;
    }
    break;
  case VCExpr::Not:
    OS << "¬";
    printVCExprLean(E->Children[0].get(), OS, 10);
    break;
  case VCExpr::And:
    paren(3, [&] {
      for (unsigned I = 0; I < E->Children.size(); ++I) {
        if (I)
          OS << " ∧ ";
        printVCExprLean(E->Children[I].get(), OS, 3);
      }
    });
    break;
  case VCExpr::Or:
    paren(2, [&] {
      for (unsigned I = 0; I < E->Children.size(); ++I) {
        if (I)
          OS << " ∨ ";
        printVCExprLean(E->Children[I].get(), OS, 2);
      }
    });
    break;
  case VCExpr::Ite:
    paren(1, [&] {
      OS << "if ";
      printVCExprLean(E->Children[0].get(), OS, 0);
      OS << " then ";
      printVCExprLean(E->Children[1].get(), OS, 0);
      OS << " else ";
      printVCExprLean(E->Children[2].get(), OS, 0);
    });
    break;
  case VCExpr::Eq:
    paren(5, [&] {
      printVCExprLean(E->Children[0].get(), OS, 5);
      OS << " = ";
      printVCExprLean(E->Children[1].get(), OS, 5);
    });
    break;
  case VCExpr::Ne:
    paren(5, [&] {
      printVCExprLean(E->Children[0].get(), OS, 5);
      OS << " ≠ ";
      printVCExprLean(E->Children[1].get(), OS, 5);
    });
    break;
  case VCExpr::Lt:
    paren(6, [&] {
      printVCExprLean(E->Children[0].get(), OS, 6);
      OS << " < ";
      printVCExprLean(E->Children[1].get(), OS, 6);
    });
    break;
  case VCExpr::Le:
    paren(6, [&] {
      printVCExprLean(E->Children[0].get(), OS, 6);
      OS << " ≤ ";
      printVCExprLean(E->Children[1].get(), OS, 6);
    });
    break;
  case VCExpr::Gt:
    paren(6, [&] {
      printVCExprLean(E->Children[0].get(), OS, 6);
      OS << " > ";
      printVCExprLean(E->Children[1].get(), OS, 6);
    });
    break;
  case VCExpr::Ge:
    paren(6, [&] {
      printVCExprLean(E->Children[0].get(), OS, 6);
      OS << " ≥ ";
      printVCExprLean(E->Children[1].get(), OS, 6);
    });
    break;
  case VCExpr::Add:
    paren(7, [&] {
      printVCExprLean(E->Children[0].get(), OS, 7);
      OS << " + ";
      printVCExprLean(E->Children[1].get(), OS, 7);
    });
    break;
  case VCExpr::Sub:
    paren(7, [&] {
      printVCExprLean(E->Children[0].get(), OS, 7);
      OS << " - ";
      printVCExprLean(E->Children[1].get(), OS, 7);
    });
    break;
  case VCExpr::Mul:
    paren(8, [&] {
      printVCExprLean(E->Children[0].get(), OS, 8);
      OS << " * ";
      printVCExprLean(E->Children[1].get(), OS, 8);
    });
    break;
  case VCExpr::Neg:
    OS << "-";
    printVCExprLean(E->Children[0].get(), OS, 9);
    break;
  case VCExpr::Select:
    OS << "heapSelect ";
    printVCExprLean(E->Children[0].get(), OS, 0);
    OS << " ";
    printVCExprLean(E->Children[1].get(), OS, 0);
    break;
  case VCExpr::Store:
    OS << "heapStore ";
    printVCExprLean(E->Children[0].get(), OS, 0);
    OS << " ";
    printVCExprLean(E->Children[1].get(), OS, 0);
    OS << " ";
    printVCExprLean(E->Children[2].get(), OS, 0);
    OS << " ";
    printVCExprLean(E->Children[3].get(), OS, 0);
    break;
  case VCExpr::Forall:
    OS << "True";
    break;
  }
}

VerifyResult verify::exportLeanScratchPad(const PassiveProgram &P,
                                          llvm::raw_ostream &OS,
                                          unsigned SolverTimeoutMs) {
  VCMachine M = VCMachine::fromPassive(P);
  Z3VerifyBackend Z3(SolverTimeoutMs);
  VerifyResult Z3R = Z3.verifyPassive(P);

  OS << "/- Generated by CppVerify (Lean scratch-pad). Proof obligations only. -/\n";
  OS << "/- Z3 check: ";
  switch (Z3R.Status) {
  case VerifyStatus::Verified:
    OS << "verified";
    break;
  case VerifyStatus::Failed:
    OS << "failed";
    if (!Z3R.Message.empty())
      OS << " — counterexample hint: " << Z3R.Message;
    break;
  default:
    OS << "unknown";
    break;
  }
  OS << " -/\n\n";

  OS << "def heapSelect (h : Array Int Int) (p : Int) : Int := h[p]!\n";
  OS << "def heapStore (h : Array Int Int) (p : Int) (v : Int) (h' : Array Int Int) : Prop :=\n";
  OS << "  h' = h.set! p v\n\n";

  OS << "theorem cppverify_goal : ";
  LeanEmitBudget = 500000;
  printVCExprLean(M.Goal.get(), OS);
  OS << " := by\n  sorry\n";

  VerifyResult R;
  R.Status = VerifyStatus::Verified;
  R.Message = "lean export written";
  return R;
}