// RUN: rm -rf %t.project
// RUN: %cpp-verify --backend=lean --lean-project=%t.project %s 2>&1 | FileCheck %s --check-prefix=EXPORT
// RUN: test -f %t.project/lean-toolchain
// RUN: test -f %t.project/lakefile.toml
// RUN: test -f %t.project/CppVerify/Generated.lean
// RUN: test -f %t.project/CppVerify/User.lean
// RUN: test -f %t.project/CppVerify/Check.lean
// RUN: test -f %t.project/CppVerify/Proofs/Goal_583ed320b83a75f8.lean
// RUN: grep -Fxq 'leanprover/lean4:v4.32.2' %t.project/lean-toolchain
// RUN: FileCheck %s --input-file=%t.project/CppVerify/Generated.lean --check-prefix=GENERATED
// RUN: grep -Fq 'import CppVerify.Proofs.Goal_583ed320b83a75f8' %t.project/CppVerify/Check.lean
// RUN: echo '/- USER_KEEP -/' >> %t.project/CppVerify/User.lean
// RUN: echo '/- PROOF_KEEP -/' >> %t.project/CppVerify/Proofs/Goal_583ed320b83a75f8.lean
// RUN: %cpp-verify --backend=lean --lean-project=%t.project %s 2>&1 | FileCheck %s --check-prefix=EXPORT
// RUN: grep -Fq 'USER_KEEP' %t.project/CppVerify/User.lean
// RUN: grep -Fq 'PROOF_KEEP' %t.project/CppVerify/Proofs/Goal_583ed320b83a75f8.lean
// RUN: echo 'leanprover/lean4:v4.31.0' > %t.project/lean-toolchain
// RUN: not %cpp-verify --backend=lean --lean-project=%t.project %s 2>&1 | FileCheck %s --check-prefix=PIN
// RUN: not %cpp-verify --backend=lean --lean-project=%t.empty --lean-certify %S/Inputs/lean_no_obligations.cpp 2>&1 | FileCheck %s --check-prefix=EMPTY

void trivial()
  post(true)
{}

// EXPORT: Exported: lean obligation: trivial
// GENERATED: Generated by CppVerify for an editable Lean project.
// GENERATED-NOT: unchecked Lean scratch-pad
// GENERATED: function: trivial
// GENERATED: source: {{.*}}lean_project.cpp:{{[0-9]+:[0-9]+}}
// PIN: Lean project uses toolchain 'leanprover/lean4:v4.31.0'; expected 'leanprover/lean4:v4.32.2'
// EMPTY: Unresolved: Lean certification requires at least one proof obligation
